const fs = require('fs');
const path = require('path');

const locales = ['en', 'tr', 'de', 'fr', 'sk', 'it'];

const dict = {
    en: {
        addCategory: "+ Add New Category",
        addCategoryTitle: "Add Category",
        addCategoryExample: "Ex: Main Courses",
        add: "Add",
        cancel: "Cancel",
        productAdd: "+ Add Product",
        productEmpty: "No products in this category.",
        available: "✅ Available",
        outOfStock: "⛔ Out of Stock",
        delete: "Delete",
        qrCodeBtn: "QR Code",
        qrCardTitle: "QR Menu Card",
        qrDownloadBtn: "Download QR (PNG)",
        staffManagement: "👨‍🍳 Staff Management",
        staffDesc: "Add your team members here.",
        nameSurname: "Full Name",
        emailOptional: "Email (Optional)",
        phoneOptional: "Phone (Optional)",
        addStaffBtn: "+ Add",
        whiteMode: "☀️ Light Mode",
        darkMode: "🌙 Dark Mode",
        eyeComfort: "👁️ Eye Comfort",
        brandAppearance: "Brand & Appearance",
        dailyStatus: "Daily Restaurant Status",
        openNow: "Currently OPEN ✅",
        closedNow: "Currently CLOSED ⛔",
        canOrder: "Customers can order.",
        warnClosed: "Shows 'Closed' warning on menu.",
        saveStatus: "Save Status",
        saveBrand: "Save Brand Settings",
        corpComm: "Corporate & Communication",
        authPerson: "Authorized Person",
        companyName: "Company Name",
        saveComm: "Save Communication Info",
        dailyCampaign: "🎉 Daily Campaign / Announcement",
        campaignActive: "Activate Campaign",
        campaignTitleLabel: "Title (Ex: Happy Friday!)",
        campaignTextLabel: "Campaign Details",
        saveCampaign: "Save Campaign",
        menuAppearance: "Menu Appearance",
        caloriesInfo: "Calories Info",
        prepTime: "Preparation Time",
        saveAppearance: "Save Appearance",
        adminPanelHeader: "🔒 Admin Panel (Admins Only)",
        licenseStatus: "License Status (Active/Passive)",
        subEndDate: "Subscription End Date",
        paymentSystem: "💳 Payment System (Stripe)",
        onlinePayment: "Online Payment",
        onlinePaymentDesc: "Allows receiving payments at the table.",
        saveSystem: "Save System Settings"
    },
    tr: {
        addCategory: "+ Yeni Kategori Ekle",
        addCategoryTitle: "Kategori Ekle",
        addCategoryExample: "Örn: Ana Yemekler",
        add: "Ekle",
        cancel: "İptal",
        productAdd: "+ Ürün Ekle",
        productEmpty: "Bu kategoride ürün yok.",
        available: "✅ Mevcut",
        outOfStock: "⛔ Tükendi",
        delete: "Sil",
        qrCodeBtn: "QR Kod",
        qrCardTitle: "QR Menü Kartı",
        qrDownloadBtn: "QR Kodu İndir (PNG)",
        staffManagement: "👨‍🍳 Personel Yönetimi",
        staffDesc: "Ekip çalışanlarınızı buraya ekleyin.",
        nameSurname: "Ad Soyad",
        emailOptional: "E-Posta (Opsiyonel)",
        phoneOptional: "Telefon (Opsiyonel)",
        addStaffBtn: "+ Ekle",
        whiteMode: "☀️ Beyaz Mod",
        darkMode: "🌙 Dark Mode",
        eyeComfort: "👁️ Göz Koruması",
        brandAppearance: "Marka & Görünüm",
        dailyStatus: "Restoran Günlük Durumu",
        openNow: "Şu an AÇIK ✅",
        closedNow: "Şu an KAPALI ⛔",
        canOrder: "Müşteriler sipariş verebilir.",
        warnClosed: "Menüde 'Kapalı' uyarısı görünür.",
        saveStatus: "Durumu Kaydet",
        saveBrand: "Marka Ayarlarını Kaydet",
        corpComm: "Kurumsal & İletişim",
        authPerson: "Yetkili Kişi",
        companyName: "Şirket Ünvanı",
        saveComm: "İletişim Bilgilerini Kaydet",
        dailyCampaign: "🎉 Günün Kampanyası / Duyuru",
        campaignActive: "Kampanyayı Aktif Et",
        campaignTitleLabel: "Başlık (Örn: Mutlu Cuma!)",
        campaignTextLabel: "Kampanya Metni",
        saveCampaign: "Kampanyayı Kaydet",
        menuAppearance: "Menü Görünümü",
        caloriesInfo: "Kalori Bilgisi",
        prepTime: "Hazırlanma Süresi",
        saveAppearance: "Görünümü Kaydet",
        adminPanelHeader: "🔒 Yönetici Paneli (Sadece Admin)",
        licenseStatus: "Lisans Durumu (Aktif/Pasif)",
        subEndDate: "Abonelik Bitiş Tarihi",
        paymentSystem: "💳 Ödeme Sistemi (Stripe)",
        onlinePayment: "Online Ödeme",
        onlinePaymentDesc: "Restoranın masada ödeme almasını sağlar.",
        saveSystem: "Sistem Ayarlarını Kaydet"
    },
    de: {
        addCategory: "+ Neue Kategorie hinzufügen",
        addCategoryTitle: "Kategorie hinzufügen",
        addCategoryExample: "Z.B.: Hauptgerichte",
        add: "Hinzufügen",
        cancel: "Abbrechen",
        productAdd: "+ Produkt hinzufügen",
        productEmpty: "Keine Produkte in dieser Kategorie.",
        available: "✅ Verfügbar",
        outOfStock: "⛔ Ausverkauft",
        delete: "Löschen",
        qrCodeBtn: "QR-Code",
        qrCardTitle: "QR-Menü-Karte",
        qrDownloadBtn: "QR (PNG) herunterladen",
        staffManagement: "👨‍🍳 Personalverwaltung",
        staffDesc: "Fügen Sie hier Ihre Teammitglieder hinzu.",
        nameSurname: "Vor- und Nachname",
        emailOptional: "E-Mail (optional)",
        phoneOptional: "Telefon (optional)",
        addStaffBtn: "+ Hinzufügen",
        whiteMode: "☀️ Heller Modus",
        darkMode: "🌙 Dunkler Modus",
        eyeComfort: "👁️ Augenkomfort",
        brandAppearance: "Marke & Aussehen",
        dailyStatus: "Täglicher Restaurantstatus",
        openNow: "Derzeit GEÖFFNET ✅",
        closedNow: "Derzeit GESCHLOSSEN ⛔",
        canOrder: "Kunden können bestellen.",
        warnClosed: "Zeigt die Warnung 'Geschlossen' auf dem Menü an.",
        saveStatus: "Status speichern",
        saveBrand: "Markeneinstellungen speichern",
        corpComm: "Unternehmen & Kommunikation",
        authPerson: "Autorisierte Person",
        companyName: "Firmenname",
        saveComm: "Kommunikationsinfo speichern",
        dailyCampaign: "🎉 Tägliche Kampagne / Ankündigung",
        campaignActive: "Kampagne aktivieren",
        campaignTitleLabel: "Titel (Z.B.: Fröhlicher Freitag!)",
        campaignTextLabel: "Kampagnendetails",
        saveCampaign: "Kampagne speichern",
        menuAppearance: "Menü-Erscheinungsbild",
        caloriesInfo: "Kalorieninfo",
        prepTime: "Zubereitungszeit",
        saveAppearance: "Aussehen speichern",
        adminPanelHeader: "🔒 Admin-Panel (nur für Administratoren)",
        licenseStatus: "Lizenzstatus (Aktiv/Passiv)",
        subEndDate: "Abonnement-Enddatum",
        paymentSystem: "💳 Zahlungssystem (Stripe)",
        onlinePayment: "Online-Bezahlung",
        onlinePaymentDesc: "Ermöglicht den Empfang von Zahlungen am Tisch.",
        saveSystem: "Systemeinstellungen speichern"
    },
    fr: {
        addCategory: "+ Ajouter une catégorie",
        addCategoryTitle: "Ajouter la catégorie",
        addCategoryExample: "Ex: Plats principaux",
        add: "Ajouter",
        cancel: "Annuler",
        productAdd: "+ Ajouter un produit",
        productEmpty: "Aucun produit dans cette catégorie.",
        available: "✅ Disponible",
        outOfStock: "⛔ En rupture de stock",
        delete: "Supprimer",
        qrCodeBtn: "Code QR",
        qrCardTitle: "Carte de menu QR",
        qrDownloadBtn: "Télécharger QR (PNG)",
        staffManagement: "👨‍🍳 Gestion du personnel",
        staffDesc: "Ajoutez les membres de votre équipe ici.",
        nameSurname: "Nom complet",
        emailOptional: "E-mail (Facultatif)",
        phoneOptional: "Téléphone (Facultatif)",
        addStaffBtn: "+ Ajouter",
        whiteMode: "☀️ Mode clair",
        darkMode: "🌙 Mode sombre",
        eyeComfort: "👁️ Confort des yeux",
        brandAppearance: "Marque et apparence",
        dailyStatus: "Statut quotidien du restaurant",
        openNow: "Actuellement OUVERT ✅",
        closedNow: "Actuellement FERMÉ ⛔",
        canOrder: "Les clients peuvent commander.",
        warnClosed: "Affiche l'avertissement 'Fermé' sur le menu.",
        saveStatus: "Enregistrer l'état",
        saveBrand: "Enregistrer les paramètres de marque",
        corpComm: "Entreprise et communication",
        authPerson: "Personne autorisée",
        companyName: "Nom de l'entreprise",
        saveComm: "Enregistrer les informations de communication",
        dailyCampaign: "🎉 Campagne quotidienne",
        campaignActive: "Activer la campagne",
        campaignTitleLabel: "Titre (Ex : Joyeux vendredi !)",
        campaignTextLabel: "Détails de la campagne",
        saveCampaign: "Enregistrer la campagne",
        menuAppearance: "Apparence du menu",
        caloriesInfo: "Informations sur les calories",
        prepTime: "Temps de préparation",
        saveAppearance: "Enregistrer l'apparence",
        adminPanelHeader: "🔒 Panneau d'administration",
        licenseStatus: "Statut de licence (Actif/Passif)",
        subEndDate: "Date de fin d'abonnement",
        paymentSystem: "💳 Système de paiement (Stripe)",
        onlinePayment: "Paiement en ligne",
        onlinePaymentDesc: "Permet de recevoir des paiements à table.",
        saveSystem: "Enregistrer le système"
    },
    sk: {
        addCategory: "+ Pridať novú kategóriu",
        addCategoryTitle: "Pridať kategóriu",
        addCategoryExample: "Napr.: Hlavné jedlá",
        add: "Pridať",
        cancel: "Zrušiť",
        productAdd: "+ Pridať produkt",
        productEmpty: "Žiadne produkty v tejto kategórii.",
        available: "✅ K dispozícii",
        outOfStock: "⛔ Vypredané",
        delete: "Vymazať",
        qrCodeBtn: "QR Kód",
        qrCardTitle: "QR Menu Karta",
        qrDownloadBtn: "Stiahnuť QR (PNG)",
        staffManagement: "👨‍🍳 Správa personálu",
        staffDesc: "Tu pridajte členov svojho tímu.",
        nameSurname: "Meno a priezvisko",
        emailOptional: "E-mail (voliteľné)",
        phoneOptional: "Telefón (voliteľné)",
        addStaffBtn: "+ Pridať",
        whiteMode: "☀️ Svetlý režim",
        darkMode: "🌙 Tmavý režim",
        eyeComfort: "👁️ Komfort pre oči",
        brandAppearance: "Značka a vzhľad",
        dailyStatus: "Denný stav reštaurácie",
        openNow: "Momentálne OTVORENÉ ✅",
        closedNow: "Momentálne ZATVORENÉ ⛔",
        canOrder: "Zákazníci si môžu objednať.",
        warnClosed: "Zobrazuje upozornenie 'Zatvorené' v menu.",
        saveStatus: "Uložiť stav",
        saveBrand: "Uložiť nastavenia značky",
        corpComm: "Spoločnosť a komunikácia",
        authPerson: "Oprávnená osoba",
        companyName: "Názov spoločnosti",
        saveComm: "Uložiť kontaktné údaje",
        dailyCampaign: "🎉 Denná kampaň / Oznámenie",
        campaignActive: "Aktivovať kampaň",
        campaignTitleLabel: "Názov (Napr.: Šťastný piatok!)",
        campaignTextLabel: "Podrobnosti kampane",
        saveCampaign: "Uložiť kampaň",
        menuAppearance: "Vzhľad menu",
        caloriesInfo: "Informácie o kalóriách",
        prepTime: "Čas prípravy",
        saveAppearance: "Uložiť vzhľad",
        adminPanelHeader: "🔒 Admin panel (Len pre adminov)",
        licenseStatus: "Stav licencie (Aktívny/Pasívny)",
        subEndDate: "Dátum konca predplatného",
        paymentSystem: "💳 Platobný systém (Stripe)",
        onlinePayment: "Platba online",
        onlinePaymentDesc: "Umožňuje prijímať platby pri stole.",
        saveSystem: "Uložiť systémové nastavenia"
    },
    it: {
        addCategory: "+ Aggiungi Nuova Categoria",
        addCategoryTitle: "Aggiungi Categoria",
        addCategoryExample: "Es: Piatti Principali",
        add: "Aggiungi",
        cancel: "Annulla",
        productAdd: "+ Aggiungi Prodotto",
        productEmpty: "Nessun prodotto in questa categoria.",
        available: "✅ Disponibile",
        outOfStock: "⛔ Esaurito",
        delete: "Elimina",
        qrCodeBtn: "Codice QR",
        qrCardTitle: "Scheda Menu QR",
        qrDownloadBtn: "Scarica QR (PNG)",
        staffManagement: "👨‍🍳 Gestione del Personale",
        staffDesc: "Aggiungi qui i membri del tuo team.",
        nameSurname: "Nome e Cognome",
        emailOptional: "E-mail (Opzionale)",
        phoneOptional: "Telefono (Opzionale)",
        addStaffBtn: "+ Aggiungi",
        whiteMode: "☀️ Modalità Chiara",
        darkMode: "🌙 Modalità Scura",
        eyeComfort: "👁️ Comfort visivo",
        brandAppearance: "Marchio e Aspetto",
        dailyStatus: "Stato Giornaliero del Ristorante",
        openNow: "Attualmente APERTO ✅",
        closedNow: "Attualmente CHIUSO ⛔",
        canOrder: "I clienti possono ordinare.",
        warnClosed: "Mostra l'avviso 'Chiuso' sul menu.",
        saveStatus: "Salva Stato",
        saveBrand: "Salva Impostazioni Marchio",
        corpComm: "Azienda e Comunicazione",
        authPerson: "Persona Autorizzata",
        companyName: "Nome dell'Azienda",
        saveComm: "Salva Informazioni di Comunicazione",
        dailyCampaign: "🎉 Campagna Giornaliera",
        campaignActive: "Attiva Campagna",
        campaignTitleLabel: "Titolo (Es: Buon Venerdì!)",
        campaignTextLabel: "Dettagli Campagna",
        saveCampaign: "Salva Campagna",
        menuAppearance: "Aspetto del Menu",
        caloriesInfo: "Informazioni sulle Calorie",
        prepTime: "Tempo di Preparazione",
        saveAppearance: "Salva Aspetto",
        adminPanelHeader: "🔒 Pannello di Amministrazione",
        licenseStatus: "Stato della Licenza (Attivo/Passivo)",
        subEndDate: "Data di Fine Abbonamento",
        paymentSystem: "💳 Sistema di Pagamento (Stripe)",
        onlinePayment: "Pagamento Online",
        onlinePaymentDesc: "Consente di ricevere pagamenti al tavolo.",
        saveSystem: "Salva Impostazioni di Sistema"
    }
};

locales.forEach(loc => {
    const filePath = path.join('c:\\projelerim\\stil_kocum\\qr-menu-saas\\messages', `${loc}.json`);
    let content = {};
    if (fs.existsSync(filePath)) {
        content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    }

    if (!content.components) content.components = {};
    content.components = { ...content.components, ...dict[loc] };

    fs.writeFileSync(filePath, JSON.stringify(content, null, 4), 'utf8');
    console.log(`Updated ${loc}.json`);
});
