const fs = require('fs');
const path = require('path');

const locales = ['en', 'tr', 'de', 'fr', 'sk', 'it'];

const dict = {
    en: {
        restaurantName: "Restaurant Name",
        restaurantLogo: "Restaurant Logo",
        coverPhoto: "Cover Photo (Restaurant Vitrine)",
        urlSlug: "URL Short Name (Slug)",
        address: "Address",
        currency: "Currency",
        chooseFile: "Choose File",
        noFileSelected: "No file selected",
        idealDimensions: "💡 Ideal Dimensions (Global Standard)",
        squareFormatHint: "Square format, ~800px width recommended. Auto-enhancement active.",
        cinematicFormatHint: "16:9 Cinematic format, ~1600px width recommended. Auto-enhancement active."
    },
    tr: {
        restaurantName: "Restoran Adı",
        restaurantLogo: "Restoran Logosu",
        coverPhoto: "Kapak Fotoğrafı (Restoran Vitrini)",
        urlSlug: "URL Kısa Adı (Slug)",
        address: "Adres",
        currency: "Para Birimi",
        chooseFile: "Dosya Seç",
        noFileSelected: "Dosya seçilmedi",
        idealDimensions: "💡 İdeal Boyutlar (Global Standart)",
        squareFormatHint: "1:1 Kare formatında, ~800px genişliğinde yüklemeniz önerilir. Otomatik iyileştirme aktif.",
        cinematicFormatHint: "16:9 Sinematik formatında, ~1600px genişliğinde yüklemeniz önerilir. Otomatik iyileştirme aktif."
    },
    de: {
        restaurantName: "Restaurantname",
        restaurantLogo: "Restaurant-Logo",
        coverPhoto: "Titelbild",
        urlSlug: "URL-Kurzname (Slug)",
        address: "Adresse",
        currency: "Währung",
        chooseFile: "Datei wählen",
        noFileSelected: "Keine Datei ausgewählt",
        idealDimensions: "💡 Ideale Abmessungen (Globaler Standard)",
        squareFormatHint: "Quadratisches Format, ~800px Breite empfohlen. Automatische Verbesserung aktiv.",
        cinematicFormatHint: "16:9 Format, ~1600px Breite empfohlen. Automatische Verbesserung aktiv."
    },
    fr: {
        restaurantName: "Nom du Restaurant",
        restaurantLogo: "Logo du Restaurant",
        coverPhoto: "Photo de Couverture",
        urlSlug: "Nom court URL (Slug)",
        address: "Adresse",
        currency: "Devise",
        chooseFile: "Choisir un Fichier",
        noFileSelected: "Aucun fichier sélectionné",
        idealDimensions: "💡 Dimensions Idéales (Standard Mondial)",
        squareFormatHint: "Format carré, largeur de ~800px recommandée. Amélioration automatique active.",
        cinematicFormatHint: "Format 16:9, largeur de ~1600px recommandée. Amélioration automatique active."
    },
    sk: {
        restaurantName: "Názov Reštaurácie",
        restaurantLogo: "Logo Reštaurácie",
        coverPhoto: "Titulná Fotografia",
        urlSlug: "Krátky názov URL (Slug)",
        address: "Adresa",
        currency: "Mena",
        chooseFile: "Vybrať Súbor",
        noFileSelected: "Žiadny súbor",
        idealDimensions: "💡 Ideálne rozmery (Globálny Štandard)",
        squareFormatHint: "Odporúča sa štvorcový formát, šírka ~800px. Automatické vylepšenie je aktívne.",
        cinematicFormatHint: "Odporúča sa formát 16:9, šírka ~1600px. Automatické vylepšenie je aktívne."
    },
    it: {
        restaurantName: "Nome del Ristorante",
        restaurantLogo: "Logo del Ristorante",
        coverPhoto: "Foto di Copertina",
        urlSlug: "Nome breve URL (Slug)",
        address: "Indirizzo",
        currency: "Valuta",
        chooseFile: "Scegli File",
        noFileSelected: "Nessun file selezionato",
        idealDimensions: "💡 Dimensioni Ideali (Standard Globale)",
        squareFormatHint: "Formato quadrato, si consiglia una larghezza di ~800px. Miglioramento automatico attivo.",
        cinematicFormatHint: "Formato 16:9, si consiglia una larghezza di ~1600px. Miglioramento automatico attivo."
    }
};

const superAdminDict = {
    tr: {
        panelTitle: "QR Menu Paneli",
        mode: "SUPER ADMIN MODE",
        overview: "Sistem Genel Bakış",
        overviewDesc: "Tüm platform metriklerini ve performansını buradan izleyebilirsiniz.",
        totalRestaurants: "Toplam Restoran",
        totalProducts: "Toplam Ürün",
        activeLicenses: "Aktif Lisanslar",
        upcomingRenewals: "Yaklaşan Yenilemeler",
        licenseExpiring: "Lisans Süresi Dolmak Üzere!",
        licenseExpiringDesc: "Aşağıdaki restoranların 30 günden az süresi kaldı. Yenileme için iletişime geçin.",
        sendMail: "Mail At",
        busiestRestaurants: "En Yoğun Restoranlar (Ürün Bazlı)",
        category: "Kategori",
        productCount: "{count} Ürün",
        dataQuality: "Veri Kalitesi ve Öneriler",
        looksEmpty: "çok boş görünüyor ({count} ürün).",
        offerHelp: "Müşteriye ulaşıp menü veri girişi konusunda yardım teklif edin.",
        allGood: "Tüm restoranların veri girişi harika görünüyor!",
        allRestaurantsList: "Tüm Restoranlar Listesi",
        addNew: "+ Yeni Ekle",
        restaurant: "Restoran",
        owner: "Sahip",
        status: "Durum",
        license: "Lisans",
        statistics: "İstatistik",
        action: "İşlem",
        active: "Aktif",
        inactive: "Pasif",
        free: "Ücretsiz",
        expires: "Bitiş",
        reviews: "{count} Yorum",
        manage: "Yönet →"
    },
    en: {
        panelTitle: "QR Menu Panel",
        mode: "SUPER ADMIN MODE",
        overview: "System Overview",
        overviewDesc: "You can monitor all platform-wide metrics and performance here.",
        totalRestaurants: "Total Restaurants",
        totalProducts: "Total Products",
        activeLicenses: "Active Licenses",
        upcomingRenewals: "Upcoming Renewals",
        licenseExpiring: "Licenses Expiring Soon!",
        licenseExpiringDesc: "The following restaurants have less than 30 days left. Contact them for renewal.",
        sendMail: "Send Mail",
        busiestRestaurants: "Busiest Restaurants (By Products)",
        category: "Category",
        productCount: "{count} Products",
        dataQuality: "Data Quality & Suggestions",
        looksEmpty: "looks very empty ({count} products).",
        offerHelp: "Reach out to the client and offer help with menu data entry.",
        allGood: "Data entry for all restaurants is looking great!",
        allRestaurantsList: "All Restaurants List",
        addNew: "+ Add New",
        restaurant: "Restaurant",
        owner: "Owner",
        status: "Status",
        license: "License",
        statistics: "Statistics",
        action: "Action",
        active: "Active",
        inactive: "Inactive",
        free: "Free",
        expires: "Exp",
        reviews: "{count} Reviews",
        manage: "Manage →"
    },
    de: {
        panelTitle: "QR Menü Panel",
        mode: "SUPER ADMIN MODUS",
        overview: "Systemübersicht",
        overviewDesc: "Sie können hier alle plattformenten Metriken überschauen.",
        totalRestaurants: "Gesamte Restaurants",
        totalProducts: "Gesamte Produkte",
        activeLicenses: "Aktive Lizenzen",
        upcomingRenewals: "Baldige Erneuerungen",
        licenseExpiring: "Lizenzen laufen bald ab!",
        licenseExpiringDesc: "Die folgenden Restaurants haben weniger als 30 Tage. Kontaktieren Sie sie für eine Erneuerung.",
        sendMail: "E-Mail Senden",
        busiestRestaurants: "Ausgelastetste Restaurants",
        category: "Kategorie",
        productCount: "{count} Produkte",
        dataQuality: "Datenqualität & Vorschläge",
        looksEmpty: "sieht sehr leer aus ({count} Produkte).",
        offerHelp: "Kontaktieren Sie den Kunden und bieten Sie Hilfe an.",
        allGood: "Daten sehen großartig aus!",
        allRestaurantsList: "Alle Restaurants",
        addNew: "+ Neu Hinzufügen",
        restaurant: "Restaurant",
        owner: "Besitzer",
        status: "Status",
        license: "Lizenz",
        statistics: "Statistiken",
        action: "Aktion",
        active: "Aktiv",
        inactive: "Inaktiv",
        free: "Kostenlos",
        expires: "Ablauf",
        reviews: "{count} Bewertungen",
        manage: "Verwalten →"
    },
    fr: {
        panelTitle: "Panneau de Menu QR",
        mode: "MODE SUPER ADMIN",
        overview: "Aperçu du système",
        overviewDesc: "Surveillez les métriques ici.",
        totalRestaurants: "Restaurants Totaux",
        totalProducts: "Produits Totaux",
        activeLicenses: "Licences Actives",
        upcomingRenewals: "Renouvellements à venir",
        licenseExpiring: "Licences expirant bientôt!",
        licenseExpiringDesc: "Moins de 30 jours pour les restaurants suivants. Contactez-les.",
        sendMail: "Envoyer un e-mail",
        busiestRestaurants: "Restaurants les plus occupés",
        category: "Catégorie",
        productCount: "{count} Produits",
        dataQuality: "Qualité des données",
        looksEmpty: "semble très vide ({count} produits).",
        offerHelp: "Contactez le client et offrez de l'aide.",
        allGood: "Toutes les données sont parfaites !",
        allRestaurantsList: "Tous les restaurants",
        addNew: "+ Ajouter Nouveau",
        restaurant: "Restaurant",
        owner: "Propriétaire",
        status: "Statut",
        license: "Licence",
        statistics: "Statistiques",
        action: "Action",
        active: "Actif",
        inactive: "Inactif",
        free: "Gratuit",
        expires: "Expiration",
        reviews: "{count} Avis",
        manage: "Gérer →"
    },
    sk: {
        panelTitle: "Panel QR Menu",
        mode: "REŽIM SUPER ADMIN",
        overview: "Prehľad Systému",
        overviewDesc: "Môžete tu sledovať všetky metriky.",
        totalRestaurants: "Celkový počet reštaurácií",
        totalProducts: "Celkový počet produktov",
        activeLicenses: "Aktívne Licencie",
        upcomingRenewals: "Nadchádzajúce Obnovenia",
        licenseExpiring: "Licencie čoskoro vypršia!",
        licenseExpiringDesc: "Tieto reštaurácie majú menej ako 30 dní. Kontaktujte ich.",
        sendMail: "Odoslať E-mail",
        busiestRestaurants: "Najvyťaženejšie Reštaurácie",
        category: "Kategória",
        productCount: "{count} Produktov",
        dataQuality: "Kvalita dát a návrhy",
        looksEmpty: "vyzerá veľmi prázdne ({count} produktov).",
        offerHelp: "Oslovte klienta a ponúknite mu pomoc.",
        allGood: "Zadávanie údajov je skvelé!",
        allRestaurantsList: "Zoznam všetkých reštaurácií",
        addNew: "+ Pridať nové",
        restaurant: "Reštaurácia",
        owner: "Majiteľ",
        status: "Stav",
        license: "Licencia",
        statistics: "Štatistika",
        action: "Akcia",
        active: "Aktívne",
        inactive: "Neaktívne",
        free: "Zadarmo",
        expires: "Platnosť do",
        reviews: "{count} Recenzií",
        manage: "Spravovať →"
    },
    it: {
        panelTitle: "Pannello Menu QR",
        mode: "MODALITÀ SUPER ADMIN",
        overview: "Panoramica di Sistema",
        overviewDesc: "Puoi monitorare tutte le metriche qui.",
        totalRestaurants: "Ristoranti Totali",
        totalProducts: "Prodotti Totali",
        activeLicenses: "Licenze Attive",
        upcomingRenewals: "Prossimi Rinnovi",
        licenseExpiring: "Licenze in Scadenza!",
        licenseExpiringDesc: "I seguenti ristoranti hanno meno di 30 giorni. Contattali.",
        sendMail: "Invia E-mail",
        busiestRestaurants: "Ristoranti Più Impegnati",
        category: "Categoria",
        productCount: "{count} Prodotti",
        dataQuality: "Qualità dei Dati",
        looksEmpty: "sembra molto vuoto ({count} prodotti).",
        offerHelp: "Contatta il cliente e offriti di aiutarlo.",
        allGood: "Tutti i dati sono perfetti!",
        allRestaurantsList: "Tutti i Ristoranti",
        addNew: "+ Aggiungi Nuovo",
        restaurant: "Ristorante",
        owner: "Proprietario",
        status: "Stato",
        license: "Licenza",
        statistics: "Statistiche",
        action: "Azione",
        active: "Attivo",
        inactive: "Inattivo",
        free: "Gratis",
        expires: "Scadenza",
        reviews: "{count} Recensioni",
        manage: "Gestisci →"
    }
};


locales.forEach(loc => {
    const filePath = path.join('c:\\projelerim\\stil_kocum\\qr-menu-saas\\messages', `${loc}.json`);
    let content = {};
    if (fs.existsSync(filePath)) {
        content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    }

    if (!content.components) content.components = {};
    content.components = { ...content.components, ...dict[loc] };

    if (!content.superAdmin) content.superAdmin = {};
    content.superAdmin = { ...content.superAdmin, ...superAdminDict[loc] };

    fs.writeFileSync(filePath, JSON.stringify(content, null, 4), 'utf8');
    console.log(`Updated ${loc}.json`);
});
